export const TOKEN_KEY = '@einv-token';

export const INVOICE_TYPES_ENUM = {
  CASH_INCOME: 'CASH_INCOME',
  CASH_GENERAL_TAX: 'CASH_GENERAL_TAX',
  CASH_SPECIAL_TAX: 'CASH_SPECIAL_TAX',
  RECEIVABLE_INCOME: 'RECEIVABLE_INCOME',
  RECEIVABLE_GENERAL_TAX: 'RECEIVABLE_GENERAL_TAX',
  RECEIVABLE_SPECIAL_TAX: 'RECEIVABLE_SPECIAL_TAX',
};
export const INVOICE_TYPES = [
  'CASH_INCOME',
  'CASH_GENERAL_TAX',
  'CASH_SPECIAL_TAX',
  'RECEIVABLE_INCOME',
  'RECEIVABLE_GENERAL_TAX',
  'RECEIVABLE_SPECIAL_TAX',
];
export const INVOICE_STATUSES = ['ACTIVE', 'CANCELED'];
export const INVOICE_NOTE_TYPES = ['DEBIT_INVOICE', 'CREDIT_INVOICE'];
